version: '3'
services:
  redis-proxy:
    build: .
    network_mode: "host"
    tty: true
    ports:
      - "3000:3000"
      - "8080:8080"
  redis:
    image: "redis:alpine"
    network_mode: "host"
    ports:
      - "6379:6379"