version: '3'
services:
  redis-proxy:
    env_file:
      - redis-proxy.env
    depends_on:
      - redis
    build: .
    links:
      - "redis:redis"
    tty: true
    ports:
      - "3000:3000"
      - "8080:8080"
  redis:
    image: "redis:alpine"      