// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/redis_proxy.proto

/*
Package redisproxy is a generated protocol buffer package.

It is generated from these files:
	api/redis_proxy.proto

It has these top-level messages:
	GetItemRequest
	GetItemResponse
	ApiError
*/
package redisproxy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/struct"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetItemRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetItemRequest) Reset()                    { *m = GetItemRequest{} }
func (m *GetItemRequest) String() string            { return proto.CompactTextString(m) }
func (*GetItemRequest) ProtoMessage()               {}
func (*GetItemRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetItemRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetItemResponse struct {
	Data *google_protobuf1.Value `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *GetItemResponse) Reset()                    { *m = GetItemResponse{} }
func (m *GetItemResponse) String() string            { return proto.CompactTextString(m) }
func (*GetItemResponse) ProtoMessage()               {}
func (*GetItemResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetItemResponse) GetData() *google_protobuf1.Value {
	if m != nil {
		return m.Data
	}
	return nil
}

type ApiError struct {
	Code    int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *ApiError) Reset()                    { *m = ApiError{} }
func (m *ApiError) String() string            { return proto.CompactTextString(m) }
func (*ApiError) ProtoMessage()               {}
func (*ApiError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ApiError) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ApiError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GetItemRequest)(nil), "redisproxy.GetItemRequest")
	proto.RegisterType((*GetItemResponse)(nil), "redisproxy.GetItemResponse")
	proto.RegisterType((*ApiError)(nil), "redisproxy.ApiError")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RedisProxyService service

type RedisProxyServiceClient interface {
	GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*GetItemResponse, error)
}

type redisProxyServiceClient struct {
	cc *grpc.ClientConn
}

func NewRedisProxyServiceClient(cc *grpc.ClientConn) RedisProxyServiceClient {
	return &redisProxyServiceClient{cc}
}

func (c *redisProxyServiceClient) GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*GetItemResponse, error) {
	out := new(GetItemResponse)
	err := grpc.Invoke(ctx, "/redisproxy.RedisProxyService/GetItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RedisProxyService service

type RedisProxyServiceServer interface {
	GetItem(context.Context, *GetItemRequest) (*GetItemResponse, error)
}

func RegisterRedisProxyServiceServer(s *grpc.Server, srv RedisProxyServiceServer) {
	s.RegisterService(&_RedisProxyService_serviceDesc, srv)
}

func _RedisProxyService_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisProxyServiceServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/redisproxy.RedisProxyService/GetItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisProxyServiceServer).GetItem(ctx, req.(*GetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RedisProxyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "redisproxy.RedisProxyService",
	HandlerType: (*RedisProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItem",
			Handler:    _RedisProxyService_GetItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/redis_proxy.proto",
}

func init() { proto.RegisterFile("api/redis_proxy.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4a, 0x3b, 0x41,
	0x10, 0xc6, 0xc9, 0x91, 0xff, 0x3f, 0x3a, 0xc2, 0xa9, 0x0b, 0x86, 0xe3, 0xb4, 0x08, 0x57, 0x89,
	0xc5, 0x2e, 0xc6, 0xc6, 0xc6, 0xc2, 0x42, 0xc4, 0x4e, 0x4e, 0xb0, 0xb0, 0x91, 0xcd, 0xed, 0x78,
	0x2c, 0x24, 0x37, 0xeb, 0xee, 0x5e, 0x50, 0xc4, 0xc6, 0x57, 0xf0, 0xd1, 0x7c, 0x05, 0x1f, 0x44,
	0x6e, 0xce, 0x44, 0x04, 0xbb, 0x9d, 0xf9, 0x7e, 0xcb, 0xf7, 0x7d, 0x03, 0x7b, 0xda, 0x59, 0xe5,
	0xd1, 0xd8, 0x70, 0xef, 0x3c, 0x3d, 0x3d, 0x4b, 0xe7, 0x29, 0x92, 0x00, 0x5e, 0xf1, 0x26, 0x3f,
	0xa8, 0x89, 0xea, 0x39, 0xaa, 0x8e, 0xd4, 0x4d, 0x43, 0x51, 0x47, 0x4b, 0x4d, 0xe8, 0xc9, 0xb5,
	0xca, 0xd3, 0xac, 0x7d, 0x50, 0x21, 0xfa, 0xb6, 0x8a, 0xbd, 0x5a, 0x4c, 0x20, 0xbd, 0xc4, 0x78,
	0x15, 0x71, 0x51, 0xe2, 0x63, 0x8b, 0x21, 0x8a, 0x14, 0x12, 0x6b, 0xb2, 0xc1, 0x64, 0x70, 0xb8,
	0x59, 0x26, 0xd6, 0x14, 0x67, 0xb0, 0xbd, 0x26, 0x82, 0xa3, 0x26, 0xa0, 0x38, 0x82, 0xa1, 0xd1,
	0x51, 0x33, 0xb4, 0x35, 0x1d, 0xcb, 0xde, 0x41, 0xae, 0x1c, 0xe4, 0xad, 0x9e, 0xb7, 0x58, 0x32,
	0x53, 0x9c, 0xc2, 0xc6, 0xb9, 0xb3, 0x17, 0xde, 0x93, 0x17, 0x02, 0x86, 0x15, 0x19, 0xe4, 0x7f,
	0xff, 0x4a, 0x7e, 0x8b, 0x0c, 0x46, 0x0b, 0x0c, 0x41, 0xd7, 0x98, 0x25, 0xec, 0xb9, 0x1a, 0xa7,
	0x04, 0xbb, 0x65, 0x57, 0xf2, 0xba, 0x2b, 0x79, 0x83, 0x7e, 0x69, 0x2b, 0x14, 0x77, 0x30, 0xfa,
	0x4e, 0x23, 0x72, 0xf9, 0x73, 0x03, 0xf9, 0xbb, 0x44, 0xbe, 0xff, 0xa7, 0xd6, 0xc7, 0x2f, 0xc6,
	0x6f, 0x1f, 0x9f, 0xef, 0xc9, 0x8e, 0x48, 0xd5, 0xf2, 0x58, 0x31, 0xa2, 0x5e, 0xac, 0x79, 0x9d,
	0xfd, 0xe7, 0x02, 0x27, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x68, 0x18, 0x80, 0x73, 0x01,
	0x00, 0x00,
}
